# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beykam', '0002_auto_20161105_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='children',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='house',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='marital_status',
            field=models.CharField(blank=True, choices=[(0, b'Evli'), (1, b'Bekar'), (2, b'Dul')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='tax_exemption',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
