# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beykam', '0003_auto_20161225_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='marital_status',
            field=models.CharField(blank=True, choices=[(b'Evli', b'Evli'), (b'Bekar', b'Bekar'), (b'Dul', b'Dul')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(null=True, upload_to=b'personnel'),
        ),
    ]
