# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beykam', '0004_auto_20161225_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'personnel'),
        ),
    ]
