# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beykam', '0010_auto_20161225_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleactivity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2016, 12, 26), null=True),
        ),
    ]
