# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beykam', '0011_auto_20161226_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseactivity',
            name='total',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleactivity',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
