# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beykam', '0016_auto_20161226_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='paid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
