# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beykam', '0017_personnel_paid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
