# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beykam', '0018_inventory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='house',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2017, 1, 5), null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
