# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beykam', '0020_auto_20170105_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='children',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
